name = "BendersX"
uuid = "e6515e7d-f2f3-4cbe-b502-b49d10f04732"
authors = ["kfang <kfang11@asu.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
BendersBase = "5d493250-739e-4f20-9003-5efb7f1b28da"
BendersLibrary = "c2345678-f90a-1234-5678-901234567890"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
